library(httr)
library(jsonlite)
library(readr)
library(dplyr)
library(tidyr)
library(tidyverse)
library(tidytext)
library(ggplot2)
library(ggcorrplot)
library(glm2)
library(purrr)
library(patchwork)
library(data.table)
library(knitr)
library(kableExtra)
library(gridExtra)


data_merged <- read.csv("final_report/final_dataset.csv")
